--https://www.hackerrank.com/challenges/weather-observation-station-5/problem

--ORDER BY ORDERS BY THE NEXT COLUMN CONSTRAINT FOLLOWED BY IT
-- HERE IT ORDERS BASED ON LENGTH OF CITY NAMES
-- CITY LIMIT 1 RESTRCITS THE QUERY TO 1 RESULT
-- ORDER BY LENGTH(CITY) DESC MEANS REVERSE ORDERING

SELECT CITY, LENGTH(CITY)
FROM station 
ORDER BY LENGTH(CITY), CITY LIMIT 1; 
SELECT CITY, LENGTH(CITY)
FROM station 
ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1; 